// application
export const SHOW_CONNECT_MODAL = "SHOW_CONNECT_MODAL";
export const HIDE_CONNECT_MODAL = "HIDE_CONNECT_MODAL";
export const RESET_APP = "RESET_APP";

// user
export const ACCOUNT_UPDATED = "ACCOUNT_UPDATED";
export const ACCOUNT_LOADED = "ACCOUNT_LOADED";
export const CONNECT_INITIATED = "CONNECT_INITIATED";
export const RESET_ACCOUNT = "RESET_ACCOUNT";
export const PROVIDER_LOADED = "PROVIDER_LOADED";
export const SIGNER_LOADED = "SIGNER_LOADED";
export const DEPOSIT_INITIATED = "DEPOSIT_INITIATED";
export const WITHDRAW_INITIATED = "WITHDRAW_INITIATED";
export const BALANCE_LOADED = "BALANCE_LOADED";
export const TOKEN_BALANCES_LOADED = "TOKEN_BALANCES_LOADED";
